### PR TITLE
Customizable action that lets you send to a specific SignalR group or client method.

### PR DESCRIPTION
**Pull request by prabu2sec**

### CODE REVIEW

**Comment by sirkirby** [comment]
Any thought to getting this merged?

**Comment by nblumhardt** [comment]
@sirkirby thanks for the nudge. I think this one needs some elaboration on the scenario - it's been a long time since I looked at this sink (which is in dire need of a maintainer). Is this addressing a limitation we should be dealing with more fundamentally in how the sink is configured (i.e. is this the best way to achieve this functionality)? Cheers!

**Comment by sirkirby** [comment]
@nblumhardt Good point! So this PR is saying that rather than just sending the log message to every single client connected to a hub, it's allowing you to leverage the built in Group feature of Signalr...definitely a useful feature if you want to route your logs to specific clients while using the same Hub.

I suppose I like the option of just passing in the delegate, however, this could be simplified by passing in the string of the group name you want to target. I'll give it a look.

**Comment by sirkirby** [comment]
@prabu2sec can we close this one? We just merged PR #2 which should address you main concern of adding Groups support.

**Comment by prabu2sec** [comment]
Thanks guys. Agree, [#2](https://github.com/serilog/serilog-sinks-signalr/pull/2) is much more purpose driven than passing a do-what-you-like delegate. Shall close

**Pull request closed without merging**
